In [1]:
# imports
import numpy as np
import pandas as pd
import xarray as xr

In [2]:
# CA/NV
def ca_nv(dataarray):
    lat_drop = dataarray.where(dataarray.lat < 42, drop = True)
    lat_drop1 = lat_drop.where(lat_drop.lat > 31, drop = True)
    lon_drop2 = lat_drop1.where(lat_drop1.lon < -114, drop = True)
    return lon_drop2

In [3]:
# reading in wrf files
next_06 = ca_nv(xr.open_dataarray('./wrf_06_tmin-Copy1.nc'))
next_07 = ca_nv(xr.open_dataarray('./wrf_07_tmin-Copy1.nc'))
next_08 = ca_nv(xr.open_dataarray('./wrf_08_tmin-Copy1.nc'))
next_09 = ca_nv(xr.open_dataarray('./wrf_09_tmin-Copy1.nc'))
next_10 = ca_nv(xr.open_dataarray('./wrf_10_tmin-Copy1.nc'))
next_11 = ca_nv(xr.open_dataarray('./wrf_11_tmin-Copy1.nc'))
next_12 = ca_nv(xr.open_dataarray('./wrf_12_tmin-Copy1.nc'))
next_13 = ca_nv(xr.open_dataarray('./wrf_13_tmin-Copy1.nc'))
next_14 = ca_nv(xr.open_dataarray('./wrf_14_tmin-Copy1.nc'))
next_15 = ca_nv(xr.open_dataarray('./wrf_15_tmin-Copy1.nc'))

prev_06 = ca_nv(xr.open_dataarray('./wrf_06_tmin_prev-Copy1.nc'))
prev_07 = ca_nv(xr.open_dataarray('./wrf_07_tmin_prev-Copy1.nc'))
prev_08 = ca_nv(xr.open_dataarray('./wrf_08_tmin_prev-Copy1.nc'))
prev_09 = ca_nv(xr.open_dataarray('./wrf_09_tmin_prev-Copy1.nc'))
prev_10 = ca_nv(xr.open_dataarray('./wrf_10_tmin_prev-Copy1.nc'))
prev_11 = ca_nv(xr.open_dataarray('./wrf_11_tmin_prev-Copy1.nc'))
prev_12 = ca_nv(xr.open_dataarray('./wrf_12_tmin_prev-Copy1.nc'))
prev_13 = ca_nv(xr.open_dataarray('./wrf_13_tmin_prev-Copy1.nc'))
prev_14 = ca_nv(xr.open_dataarray('./wrf_14_tmin_prev-Copy1.nc'))
prev_15 = ca_nv(xr.open_dataarray('./wrf_15_tmin_prev-Copy1.nc'))
np.unique(next_06.data.flatten())

array([259.15922926, 261.44771766, 261.87074295, ..., 289.95943912,
       289.96097312, 289.98629265])

In [4]:
d6 = next_06.data.flatten()
d7 = next_07.data.flatten()
d8 = next_08.data.flatten()
d9 = next_09.data.flatten()
d10 = next_10.data.flatten()
d11 = next_11.data.flatten()
d12 = next_12.data.flatten()
d13 = next_13.data.flatten()
d14 = next_14.data.flatten()
d15 = next_15.data.flatten()
p6 = prev_06.data.flatten()
p7 = prev_07.data.flatten()
p8 = prev_08.data.flatten()
p9 = prev_09.data.flatten()
p10 = prev_10.data.flatten()
p11 = prev_11.data.flatten()
p12 = prev_12.data.flatten()
p13 = prev_13.data.flatten()
p14 = prev_14.data.flatten()
p15 = prev_15.data.flatten()

bn_data = {
          'n6': d6, 'n7': d7, 'n8': d7, 'n9': d9, 'n10': d10, 'n11': d11, 'n12': d12, 'n13': d13, 'n14': d14, 'n15': d15,
          'p6': p6, 'p7': p7, 'p8': p7, 'p9': p9, 'p10': p10, 'p11': p11, 'p12': p12, 'p13': p13, 'p14': p14, 'p15': p15}
       
bn = pd.DataFrame(bn_data)
solid = pd.DataFrame(bn_data)
print(bn)
np.unique(bn.values.flatten())

               n6          n7          n8          n9         n10         n11  \
0      289.621500  289.480150  289.480150  289.545499  287.742975  286.379061   
1      289.551153  289.502427  289.502427  289.541782  287.649393  286.379752   
2      289.601325  289.471336  289.471336  289.517515  287.737536  286.369857   
3      289.689847  289.395148  289.395148  289.480035  287.641886  286.370830   
4      289.705218  289.367800  289.367800  289.464348  287.522945  286.315399   
...           ...         ...         ...         ...         ...         ...   
29915  271.662847  268.713906  268.713906  275.855377  272.339283  266.210055   
29916  272.420862  269.923848  269.923848  275.630602  273.606228  267.486266   
29917  272.579424  270.987303  270.987303  275.897028  274.338687  268.359779   
29918  273.154395  271.435341  271.435341  276.618983  275.247444  269.408054   
29919  273.709466  272.114687  272.114687  277.224955  276.039526  270.072455   

              n12         n

array([256.61533892, 256.69780209, 256.8704688 , ..., 292.97331619,
       293.01957689, 293.17627782])

In [5]:
pre_bias = pd.DataFrame()

def diff(num_str, day, table, out):
    fn = '/cw3e/mead/projects/cwp103/scratch/ldehaan/Livneh/ptt_2017.nc'
    liv_file = xr.open_dataset(fn)
    liv = ca_nv(liv_file['Tmin'][day]).data.flatten()
    table[num_str][table[num_str] == 0.0] = np.NAN
    table[num_str] = table[num_str] - 273.15
    subtr = np.subtract(np.array(table[num_str]), liv)
    out[num_str] = subtr

liv_days = [36,37,38,39,40,41,42,43,44,45]#[::-1] #experiment
days_next = ['n6','n7','n8','n9','n10','n11','n12','n13','n14','n15']
days_prev = ['p6','p7','p8','p9','p10','p11','p12','p13','p14','p15']
for j in np.arange(10):
    diff(days_next[j], liv_days[j], bn, pre_bias)
    diff(days_prev[j], liv_days[j], bn, pre_bias)
print(pre_bias)
min(np.unique(pre_bias.values.flatten())), np.unique(solid.values.flatten())

             n6        p6        n7        p7        n8        p8        n9  \
0           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
3           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
4           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...         ...       ...       ...       ...       ...       ...       ...   
29915  0.764476  1.618343 -0.014465  2.934476 -0.074465  2.874476  3.517006   
29916  0.761866  0.412758  0.424852  2.921866  0.364852  2.861866  2.501606   
29917  0.334702 -0.124118  0.922581  2.514702  0.862581  2.454702  2.172305   
29918 -0.110280 -0.216731  0.400666  2.119720  0.340666  2.059720  1.874308   
29919 -0.775858 -0.508856  0.909362  2.504142  0.809362  2.404142  2.019631   

             p9       n10       p10       n11      

(-11.342148642115262,
 array([256.61533892, 256.69780209, 256.8704688 , ..., 292.97331619,
        293.01957689, 293.17627782]))

In [6]:
init_bias_next = pre_bias['n6'] + pre_bias['n7'] + pre_bias['n8'] + pre_bias['n9'] + pre_bias['n10'] + pre_bias['n11'] + pre_bias['n12'] + pre_bias['n13'] + pre_bias['n14'] + pre_bias['n15']
init_bias_next = init_bias_next / 10
init_bias_next

0             NaN
1             NaN
2             NaN
3             NaN
4             NaN
           ...   
29915    2.607463
29916    2.795007
29917    2.493796
29918    2.167717
29919    2.296894
Length: 29920, dtype: float64

In [7]:
init_bias_prev = pre_bias['p6'] + pre_bias['p7'] + pre_bias['p8'] + pre_bias['p9'] + pre_bias['p10'] + pre_bias['p11'] + pre_bias['p12'] + pre_bias['p13'] + pre_bias['p14'] + pre_bias['p15']
init_bias_prev = init_bias_prev / 10
np.unique(init_bias_next.values.flatten())

array([-5.17052229, -5.0761883 , -5.0671012 , ...,         nan,
               nan,         nan])

In [8]:
solid['Bias Next'] = init_bias_next
solid['Bias Previous'] = init_bias_prev
print(solid)
min(np.unique(solid['n6'].values.flatten()))

               n6          n7          n8          n9         n10         n11  \
0      289.621500  289.480150  289.480150  289.545499  287.742975  286.379061   
1      289.551153  289.502427  289.502427  289.541782  287.649393  286.379752   
2      289.601325  289.471336  289.471336  289.517515  287.737536  286.369857   
3      289.689847  289.395148  289.395148  289.480035  287.641886  286.370830   
4      289.705218  289.367800  289.367800  289.464348  287.522945  286.315399   
...           ...         ...         ...         ...         ...         ...   
29915  271.662847  268.713906  268.713906  275.855377  272.339283  266.210055   
29916  272.420862  269.923848  269.923848  275.630602  273.606228  267.486266   
29917  272.579424  270.987303  270.987303  275.897028  274.338687  268.359779   
29918  273.154395  271.435341  271.435341  276.618983  275.247444  269.408054   
29919  273.709466  272.114687  272.114687  277.224955  276.039526  270.072455   

              n12         n

259.1592292568164

In [9]:
out_bias = pd.DataFrame()

def smallest_magnitude(next_dif, prev_dif, w_next, w_prev):
    if abs(prev_dif) < abs(next_dif):
        return w_prev
    else:
        return w_next
    
def output_bias(num_str):
    result = []
    for x in np.arange(29920):
        temp = smallest_magnitude(solid['Bias Next'][x], solid['Bias Previous'][x], solid['n'+num_str][x], solid['p'+num_str][x])
        result.append(temp)
    out_bias[num_str] = result

days = ['6','7','8','9','10','11','12','13','14','15']
for i in np.arange(10):
    output_bias(days[i])
print(out_bias)
np.unique(out_bias.values.flatten())

                6           7           8           9          10          11  \
0      289.621500  289.480150  289.480150  289.545499  287.742975  286.379061   
1      289.551153  289.502427  289.502427  289.541782  287.649393  286.379752   
2      289.601325  289.471336  289.471336  289.517515  287.737536  286.369857   
3      289.689847  289.395148  289.395148  289.480035  287.641886  286.370830   
4      289.705218  289.367800  289.367800  289.464348  287.522945  286.315399   
...           ...         ...         ...         ...         ...         ...   
29915  271.662847  268.713906  268.713906  275.855377  272.339283  266.210055   
29916  272.420862  269.923848  269.923848  275.630602  273.606228  267.486266   
29917  272.579424  270.987303  270.987303  275.897028  274.338687  268.359779   
29918  273.154395  271.435341  271.435341  276.618983  275.247444  269.408054   
29919  273.709466  272.114687  272.114687  277.224955  276.039526  270.072455   

               12          

array([256.61533892, 256.69780209, 256.8704688 , ..., 292.97331619,
       293.01957689, 293.17627782])

In [10]:
for i in np.arange(10):
    diff(days[i], liv_days[i], out_bias, out_bias)
print(out_bias)
np.unique(out_bias.values.flatten())

              6         7         8         9        10        11        12  \
0           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
3           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
4           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...         ...       ...       ...       ...       ...       ...       ...   
29915  0.764476 -0.014465 -0.074465  3.517006 -0.069088 -2.528316  3.821190   
29916  0.761866  0.424852  0.364852  2.501606  0.427231 -2.032730  5.074134   
29917  0.334702  0.922581  0.862581  2.172305  0.573965 -1.744944  4.689222   
29918 -0.110280  0.400666  0.340666  1.874308  0.482770 -1.696621  4.553688   
29919 -0.775858  0.909362  0.809362  2.019631  0.714202 -1.452870  4.662076   

             13        14        15  
0           N

array([-11.30114536, -10.63065649, -10.13090151, ...,          nan,
                nan,          nan])

In [11]:
results = pd.DataFrame()

# average bias
sumz = 0
leng = 0
for i in days:
    temp = [x for x in np.array(out_bias[i]).flatten() if str(x) != 'nan']
    sumz += sum(np.array(temp) - 273.15)
    leng = len(temp)
avg_bias_best = sumz/(10*leng)
results['Best Bias: Bias'] = [avg_bias_best]

# rmse
def overall_rmse(dif_arr):
    sq_arr = []
    for i in dif_arr:
        sq_dif = np.square(i.data)
        sq_arr.append(sq_dif)
    arr_sq = [x for x in np.array(sq_arr).flatten() if str(x) != 'nan']
    div = sum(arr_sq) / (10*len(arr_sq))
    return np.sqrt(div)
dif_best = np.array([out_bias['6'], out_bias['7'], out_bias['8'],
         out_bias['9'], out_bias['10'],
         out_bias['11'], out_bias['12'],
         out_bias['13'], out_bias['14'],
         out_bias['15']]).flatten()
res = overall_rmse(dif_best)
results['Best Bias: RMSE'] = [res]

In [12]:
# prev
prev_out = pd.DataFrame()

prev_d = ['p6','p7','p8','p9','p10','p11','p12','p13','p14','p15']
for i in np.arange(10):
    diff(prev_d[i], liv_days[i], solid, prev_out)

summ = 0
for k in days:
    temp = [x for x in np.array(prev_out['p'+k]).flatten() if str(x) != 'nan']
    summ += sum(temp)
avg_bias_prev = summ/(10*leng)
results['Prev: Bias'] = [avg_bias_prev]

dif_prev = np.array([prev_out['p6'], prev_out['p7'], prev_out['p8'], prev_out['p9'],
                    prev_out['p10'], prev_out['p11'], prev_out['p12'], prev_out['p13'],
                    prev_out['p14'], prev_out['p15']])
res2 = overall_rmse(dif_prev)
results['Prev: RMSE'] = [res2]

In [13]:
# next
next_out = pd.DataFrame()

next_d = ['n6','n7','n8','n9','n10','n11','n12','n13','n14','n15']
for i in np.arange(10):
    diff(next_d[i], liv_days[i], solid, next_out)

summn = 0
for k in days:
    temp = [x for x in np.array(next_out['n'+k]).flatten() if str(x) != 'nan']
    summn += sum(temp)
avg_bias_next = summn/(10*leng)
results['Next: Bias'] = [avg_bias_next]

dif_next = np.array([next_out['n6'], next_out['n7'], next_out['n8'], next_out['n9'],
                    next_out['n10'], next_out['n11'], next_out['n12'], next_out['n13'],
                    next_out['n14'], next_out['n15']])
res3 = overall_rmse(dif_next)
results['Next: RMSE'] = [res3]
print(results)

   Best Bias: Bias  Best Bias: RMSE  Prev: Bias  Prev: RMSE  Next: Bias  \
0      -271.793744         1.027235    1.407942    1.058184    1.457537   

   Next: RMSE  
0    1.060626  


In [14]:
np.unique(out_bias.values.flatten())


array([-11.30114536, -10.63065649, -10.13090151, ...,          nan,
                nan,          nan])

In [15]:
bias = out_bias.values.flatten()[~np.isnan(out_bias.values.flatten())].mean()
bias

1.3562560767378775

In [16]:
sq_all = (out_bias)**2
sq_all

6         7         8          9        10        11         12  \
0           NaN       NaN       NaN        NaN       NaN       NaN        NaN   
1           NaN       NaN       NaN        NaN       NaN       NaN        NaN   
2           NaN       NaN       NaN        NaN       NaN       NaN        NaN   
3           NaN       NaN       NaN        NaN       NaN       NaN        NaN   
4           NaN       NaN       NaN        NaN       NaN       NaN        NaN   
...         ...       ...       ...        ...       ...       ...        ...   
29915  0.584424  0.000209  0.005545  12.369332  0.004773  6.392381  14.601496   
29916  0.580439  0.180499  0.133117   6.258032  0.182527  4.131992  25.746833   
29917  0.112025  0.851155  0.744045   4.718910  0.329436  3.044828  21.988801   
29918  0.012162  0.160533  0.116053   3.513030  0.233066  2.878523  20.736077   
29919  0.601956  0.826939  0.655067   4.078908  0.510085  2.110831  21.734951   

              13         14         15  
0            NaN        NaN        NaN  
1            NaN        NaN        NaN  
2            NaN        NaN        NaN  
3            NaN        NaN        NaN  
4            NaN        NaN        NaN  
...          ...        ...        ...  
29915  52.330877  65.422849  28.471208  
29916  45.557191  60.666498  34.689552  
29917  27.460738  43.302964  28.161625  
29918  23.780286  37.293729  23.509052  
29919  29.208315  31.959266  25.253744  

[29920 rows x 10 columns]

In [17]:
rmse = np.sqrt(sq_all.values.flatten()[~np.isnan(sq_all.values.flatten())].mean())
rmse

3.2484013254690423

In [18]:
prev_out

p6        p7        p8        p9       p10       p11       p12  \
0           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
3           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
4           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...         ...       ...       ...       ...       ...       ...       ...   
29915  1.618343  2.934476  2.874476 -3.055064  3.447006  3.600913  4.951684   
29916  0.412758  2.921866  2.861866 -3.859901  2.451606  4.087231  5.367270   
29917 -0.124118  2.514702  2.454702 -3.491617  2.132305  4.233965  5.595057   
29918 -0.216731  2.119720  2.059720 -5.487048  1.854308  4.142770  5.603380   
29919 -0.508856  2.504142  2.404142 -5.409709  1.899631  4.514202  5.847130   

            p13       p14       p15  
0           NaN       NaN       NaN  
1           NaN       NaN       NaN  
2           NaN       NaN       NaN  
3           NaN       NaN       NaN  
4           NaN       NaN       NaN  
...         ...       ...       ...  
29915  3.711191  6.344008  6.158439  
29916  4.954134  5.789607  5.888870  
29917  4.569222  4.190299  4.730499  
29918  4.443688  3.746503  4.286859  
29919  4.932076  4.074472  4.203252  

[29920 rows x 10 columns]

In [19]:
bias2 = prev_out.values.flatten()[~np.isnan(prev_out.values.flatten())].mean()
bias2

1.407942356205494

In [20]:
sq_all2 = prev_out**2
sq_all2

p6        p7        p8         p9        p10        p11  \
0           NaN       NaN       NaN        NaN        NaN        NaN   
1           NaN       NaN       NaN        NaN        NaN        NaN   
2           NaN       NaN       NaN        NaN        NaN        NaN   
3           NaN       NaN       NaN        NaN        NaN        NaN   
4           NaN       NaN       NaN        NaN        NaN        NaN   
...         ...       ...       ...        ...        ...        ...   
29915  2.619035  8.611151  8.262614   9.333419  11.881851  12.966571   
29916  0.170369  8.537299  8.190275  14.898836   6.010372  16.705461   
29917  0.015405  6.323724  6.025560  12.191391   4.546725  17.926457   
29918  0.046972  4.493211  4.242445  30.107698   3.438457  17.162539   
29919  0.258934  6.270726  5.779898  29.264950   3.608597  20.378019   

             p12        p13        p14        p15  
0            NaN        NaN        NaN        NaN  
1            NaN        NaN        NaN        NaN  
2            NaN        NaN        NaN        NaN  
3            NaN        NaN        NaN        NaN  
4            NaN        NaN        NaN        NaN  
...          ...        ...        ...        ...  
29915  24.519177  13.772936  40.246438  37.926370  
29916  28.807587  24.543442  33.519546  34.678785  
29917  31.304658  20.877789  17.558608  22.377620  
29918  31.397862  19.746360  14.036287  18.377164  
29919  34.188925  24.325376  16.601321  17.667331  

[29920 rows x 10 columns]

In [21]:
rmse2 = np.sqrt(sq_all2.values.flatten()[~np.isnan(sq_all2.values.flatten())].mean())
rmse2

3.346272585238879

In [22]:
next_out

n6        n7        n8        n9       n10       n11       n12  \
0           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
2           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
3           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
4           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
...         ...       ...       ...       ...       ...       ...       ...   
29915  0.764476 -0.014465 -0.074465  3.517006 -0.069088 -2.528316  3.821190   
29916  0.761866  0.424852  0.364852  2.501606  0.427231 -2.032730  5.074134   
29917  0.334702  0.922581  0.862581  2.172305  0.573965 -1.744944  4.689222   
29918 -0.110280  0.400666  0.340666  1.874308  0.482770 -1.696621  4.553688   
29919 -0.775858  0.909362  0.809362  2.019631  0.714202 -1.452870  4.662076   

            n13       n14       n15  
0           NaN       NaN       NaN  
1           NaN       NaN       NaN  
2           NaN       NaN       NaN  
3           NaN       NaN       NaN  
4           NaN       NaN       NaN  
...         ...       ...       ...  
29915  7.234008  8.088439  5.335842  
29916  6.749607  7.788870  5.889784  
29917  5.240299  6.580499  5.306753  
29918  4.876503  6.106859  4.848613  
29919  5.404472  5.653253  5.025310  

[29920 rows x 10 columns]

In [23]:
bias3 = next_out.values.flatten()[~np.isnan(next_out.values.flatten())].mean()
bias3

1.4575372991557138

In [24]:
sq_all3 = next_out**2
sq_all3

n6        n7        n8         n9       n10       n11        n12  \
0           NaN       NaN       NaN        NaN       NaN       NaN        NaN   
1           NaN       NaN       NaN        NaN       NaN       NaN        NaN   
2           NaN       NaN       NaN        NaN       NaN       NaN        NaN   
3           NaN       NaN       NaN        NaN       NaN       NaN        NaN   
4           NaN       NaN       NaN        NaN       NaN       NaN        NaN   
...         ...       ...       ...        ...       ...       ...        ...   
29915  0.584424  0.000209  0.005545  12.369332  0.004773  6.392381  14.601496   
29916  0.580439  0.180499  0.133117   6.258032  0.182527  4.131992  25.746833   
29917  0.112025  0.851155  0.744045   4.718910  0.329436  3.044828  21.988801   
29918  0.012162  0.160533  0.116053   3.513030  0.233066  2.878523  20.736077   
29919  0.601956  0.826939  0.655067   4.078908  0.510085  2.110831  21.734951   

             n13        n14        n15  
0            NaN        NaN        NaN  
1            NaN        NaN        NaN  
2            NaN        NaN        NaN  
3            NaN        NaN        NaN  
4            NaN        NaN        NaN  
...          ...        ...        ...  
29915  52.330877  65.422849  28.471208  
29916  45.557191  60.666498  34.689552  
29917  27.460738  43.302964  28.161625  
29918  23.780286  37.293729  23.509052  
29919  29.208315  31.959266  25.253744  

[29920 rows x 10 columns]

In [25]:
rmse3 = np.sqrt(sq_all3.values.flatten()[~np.isnan(sq_all3.values.flatten())].mean())
rmse3

3.3539947366123615