In [1]:
# imports
import numpy as np
import pandas as pd
import xarray as xr

In [2]:
# reading in wrf files
next_06 = xr.open_dataarray('./wrf_06_tmin-Copy1.nc')
next_07 = xr.open_dataarray('./wrf_07_tmin-Copy1.nc')
next_08 = xr.open_dataarray('./wrf_08_tmin-Copy1.nc')
next_09 = xr.open_dataarray('./wrf_09_tmin-Copy1.nc')
next_10 = xr.open_dataarray('./wrf_10_tmin-Copy1.nc')
next_11 = xr.open_dataarray('./wrf_11_tmin-Copy1.nc')
next_12 = xr.open_dataarray('./wrf_12_tmin-Copy1.nc')
next_13 = xr.open_dataarray('./wrf_13_tmin-Copy1.nc')
next_14 = xr.open_dataarray('./wrf_14_tmin-Copy1.nc')
next_15 = xr.open_dataarray('./wrf_15_tmin-Copy1.nc')

prev_06 = xr.open_dataarray('./wrf_06_tmin_prev-Copy1.nc')
prev_07 = xr.open_dataarray('./wrf_07_tmin_prev-Copy1.nc')
prev_08 = xr.open_dataarray('./wrf_08_tmin_prev-Copy1.nc')
prev_09 = xr.open_dataarray('./wrf_09_tmin_prev-Copy1.nc')
prev_10 = xr.open_dataarray('./wrf_10_tmin_prev-Copy1.nc')
prev_11 = xr.open_dataarray('./wrf_11_tmin_prev-Copy1.nc')
prev_12 = xr.open_dataarray('./wrf_12_tmin_prev-Copy1.nc')
prev_13 = xr.open_dataarray('./wrf_13_tmin_prev-Copy1.nc')
prev_14 = xr.open_dataarray('./wrf_14_tmin_prev-Copy1.nc')
prev_15 = xr.open_dataarray('./wrf_15_tmin_prev-Copy1.nc')
np.unique(next_06.data.flatten())

array([  0.        , 236.5779    , 236.73588962, ..., 290.70135353,
       290.75044928, 290.75658817])

In [3]:
d6 = next_06.data.flatten()
d7 = next_07.data.flatten()
d8 = next_08.data.flatten()
d9 = next_09.data.flatten()
d10 = next_10.data.flatten()
d11 = next_11.data.flatten()
d12 = next_12.data.flatten()
d13 = next_13.data.flatten()
d14 = next_14.data.flatten()
d15 = next_15.data.flatten()
p6 = prev_06.data.flatten()
p7 = prev_07.data.flatten()
p8 = prev_08.data.flatten()
p9 = prev_09.data.flatten()
p10 = prev_10.data.flatten()
p11 = prev_11.data.flatten()
p12 = prev_12.data.flatten()
p13 = prev_13.data.flatten()
p14 = prev_14.data.flatten()
p15 = prev_15.data.flatten()

bn_data = {
          'n6': d6, 'n7': d7, 'n8': d7, 'n9': d9, 'n10': d10, 'n11': d11, 'n12': d12, 'n13': d13, 'n14': d14, 'n15': d15,
          'p6': p6, 'p7': p7, 'p8': p7, 'p9': p9, 'p10': p10, 'p11': p11, 'p12': p12, 'p13': p13, 'p14': p14, 'p15': p15}
       
bn = pd.DataFrame(bn_data)
solid = pd.DataFrame(bn_data)
print(bn)
np.unique(bn.values.flatten())

         n6   n7   n8   n9  n10  n11  n12  n13  n14  n15   p6   p7   p8   p9  \
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
2       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
4       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
409363  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
409364  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
409365  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
409366  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
409367  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   

        p10  p11  p12  p13  p14  p15  


array([  0.        , 227.94639767, 228.09750324, ..., 293.87745456,
       293.91926321, 294.3476582 ])

In [4]:
pre_bias = pd.DataFrame()

def diff(num_str, day, table, out):
    fn = '/cw3e/mead/projects/cwp103/scratch/ldehaan/Livneh/ptt_2017.nc'
    liv_file = xr.open_dataset(fn)
    liv = liv_file['Tmin'][day].data.flatten()
    table[num_str][table[num_str] == 0.0] = np.NAN
    table[num_str] = table[num_str] - 273.15
    subtr = np.subtract(np.array(table[num_str]), liv)
    out[num_str] = subtr

liv_days = [36,37,38,39,40,41,42,43,44,45]#[::-1] #change back after experiment
days_next = ['n6','n7','n8','n9','n10','n11','n12','n13','n14','n15']
days_prev = ['p6','p7','p8','p9','p10','p11','p12','p13','p14','p15']
for j in np.arange(10):
    diff(days_next[j], liv_days[j], bn, pre_bias)
    diff(days_prev[j], liv_days[j], bn, pre_bias)
print(pre_bias)
min(np.unique(pre_bias.values.flatten())), np.unique(solid.values.flatten())

        n6  p6  n7  p7  n8  p8  n9  p9  n10  p10  n11  p11  n12  p12  n13  \
0      NaN NaN NaN NaN NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
1      NaN NaN NaN NaN NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
2      NaN NaN NaN NaN NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
3      NaN NaN NaN NaN NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
4      NaN NaN NaN NaN NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
...     ..  ..  ..  ..  ..  ..  ..  ..  ...  ...  ...  ...  ...  ...  ...   
409363 NaN NaN NaN NaN NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
409364 NaN NaN NaN NaN NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
409365 NaN NaN NaN NaN NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
409366 NaN NaN NaN NaN NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
409367 NaN NaN NaN NaN NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

        p13  n14  p14  n15  p15  
0       NaN  NaN  NaN  NaN  NaN  
1      

(-29.92432750918158,
 array([  0.        , 227.94639767, 228.09750324, ..., 293.87745456,
        293.91926321, 294.3476582 ]))

In [5]:
init_bias_next = pre_bias['n6'] + pre_bias['n7'] + pre_bias['n8'] + pre_bias['n9'] + pre_bias['n10'] + pre_bias['n11'] + pre_bias['n12'] + pre_bias['n13'] + pre_bias['n14'] + pre_bias['n15']
init_bias_next = init_bias_next / 10
init_bias_next

0        NaN
1        NaN
2        NaN
3        NaN
4        NaN
          ..
409363   NaN
409364   NaN
409365   NaN
409366   NaN
409367   NaN
Length: 409368, dtype: float64

In [6]:
init_bias_prev = pre_bias['p6'] + pre_bias['p7'] + pre_bias['p8'] + pre_bias['p9'] + pre_bias['p10'] + pre_bias['p11'] + pre_bias['p12'] + pre_bias['p13'] + pre_bias['p14'] + pre_bias['p15']
init_bias_prev = init_bias_prev / 10
np.unique(init_bias_next.values.flatten())

array([-7.23254308, -6.9591642 , -6.84960479, ...,         nan,
               nan,         nan])

In [7]:
solid['Bias Next'] = init_bias_next
solid['Bias Previous'] = init_bias_prev
print(solid)
min(np.unique(solid['n6'].values.flatten()))

         n6   n7   n8   n9  n10  n11  n12  n13  n14  n15  ...   p8   p9  p10  \
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
409363  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
409364  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
409365  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
409366  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
409367  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

        p11  p12  p13  p14  p15  Bias N

0.0

In [8]:
out_bias = pd.DataFrame()

def smallest_magnitude(next_dif, prev_dif, w_next, w_prev):
    if abs(prev_dif) < abs(next_dif):
        return w_prev
    else:
        return w_next
    
def output_bias(num_str):
    result = []
    for x in np.arange(409368):
        temp = smallest_magnitude(solid['Bias Next'][x], solid['Bias Previous'][x], solid['n'+num_str][x], solid['p'+num_str][x])
        result.append(temp)
    out_bias[num_str] = result

days = ['6','7','8','9','10','11','12','13','14','15']
for i in np.arange(10):
    output_bias(days[i])
print(out_bias)
np.unique(out_bias.values.flatten())

          6    7    8    9   10   11   12   13   14   15
0       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4       0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
409363  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
409364  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
409365  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
409366  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
409367  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[409368 rows x 10 columns]


array([  0.        , 228.91256021, 230.00339133, ..., 293.87745456,
       293.91926321, 294.3476582 ])

In [9]:
for i in np.arange(10):
    diff(days[i], liv_days[i], out_bias, out_bias)
print(out_bias)
np.unique(out_bias.values.flatten())

         6   7   8   9  10  11  12  13  14  15
0      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
1      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
2      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
3      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
4      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
...     ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
409363 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
409364 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
409365 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
409366 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
409367 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

[409368 rows x 10 columns]


array([-29.92432751, -29.70266374, -28.81360384, ...,          nan,
                nan,          nan])

In [10]:
results = pd.DataFrame()

# average bias
sumz = 0
leng = 0
for i in days:
    temp = [x for x in np.array(out_bias[i]).flatten() if str(x) != 'nan']
    sumz += sum(np.array(temp) - 273.15)
    leng = len(temp)
avg_bias_best = sumz/(10*leng)
results['Best Bias: Bias'] = [avg_bias_best]

# rmse
def overall_rmse(dif_arr):
    sq_arr = []
    for i in dif_arr:
        sq_dif = np.square(i.data)
        sq_arr.append(sq_dif)
    arr_sq = [x for x in np.array(sq_arr).flatten() if str(x) != 'nan']
    div = sum(arr_sq) / (10*len(arr_sq))
    return np.sqrt(div)
dif_best = np.array([out_bias['6'], out_bias['7'], out_bias['8'],
         out_bias['9'], out_bias['10'],
         out_bias['11'], out_bias['12'],
         out_bias['13'], out_bias['14'],
         out_bias['15']]).flatten()
res = overall_rmse(dif_best)
results['Best Bias: RMSE'] = [res]

In [11]:
# prev
prev_out = pd.DataFrame()

prev_d = ['p6','p7','p8','p9','p10','p11','p12','p13','p14','p15']
for i in np.arange(10):
    diff(prev_d[i], liv_days[i], solid, prev_out)

summ = 0
for k in days:
    temp = [x for x in np.array(prev_out['p'+k]).flatten() if str(x) != 'nan']
    summ += sum(temp)
avg_bias_prev = summ/(10*leng)
results['Prev: Bias'] = [avg_bias_prev]

dif_prev = np.array([prev_out['p6'], prev_out['p7'], prev_out['p8'], prev_out['p9'],
                    prev_out['p10'], prev_out['p11'], prev_out['p12'], prev_out['p13'],
                    prev_out['p14'], prev_out['p15']])
res2 = overall_rmse(dif_prev)
results['Prev: RMSE'] = [res2]

In [12]:
# next
next_out = pd.DataFrame()

next_d = ['n6','n7','n8','n9','n10','n11','n12','n13','n14','n15']
for i in np.arange(10):
    diff(next_d[i], liv_days[i], solid, next_out)

summn = 0
for k in days:
    temp = [x for x in np.array(next_out['n'+k]).flatten() if str(x) != 'nan']
    summn += sum(temp)
avg_bias_next = summn/(10*leng)
results['Next: Bias'] = [avg_bias_next]

dif_next = np.array([next_out['n6'], next_out['n7'], next_out['n8'], next_out['n9'],
                    next_out['n10'], next_out['n11'], next_out['n12'], next_out['n13'],
                    next_out['n14'], next_out['n15']])
res3 = overall_rmse(dif_next)
results['Next: RMSE'] = [res3]
print(results)

   Best Bias: Bias  Best Bias: RMSE  Prev: Bias  Prev: RMSE  Next: Bias  \
0      -270.944127         1.552386    2.394178    1.591451    2.332813   

   Next: RMSE  
0    1.519782  


In [13]:
np.unique(out_bias.values.flatten())


array([-29.92432751, -29.70266374, -28.81360384, ...,          nan,
                nan,          nan])

In [14]:
bias = out_bias.values.flatten()[~np.isnan(out_bias.values.flatten())].mean()
bias

2.2058726832371303

In [15]:
sq_all = (out_bias)**2
sq_all

6   7   8   9  10  11  12  13  14  15
0      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
1      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
2      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
3      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
4      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
...     ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
409363 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
409364 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
409365 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
409366 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
409367 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

[409368 rows x 10 columns]

In [16]:
rmse = np.sqrt(sq_all.values.flatten()[~np.isnan(sq_all.values.flatten())].mean())
rmse

4.909075215517081

In [17]:
prev_out

p6  p7  p8  p9  p10  p11  p12  p13  p14  p15
0      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
1      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
2      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
3      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
4      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
...     ..  ..  ..  ..  ...  ...  ...  ...  ...  ...
409363 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409364 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409365 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409366 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409367 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN

[409368 rows x 10 columns]

In [18]:
bias2 = prev_out.values.flatten()[~np.isnan(prev_out.values.flatten())].mean()
bias2

2.3941783448739535

In [19]:
sq_all2 = prev_out**2
sq_all2

p6  p7  p8  p9  p10  p11  p12  p13  p14  p15
0      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
1      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
2      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
3      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
4      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
...     ..  ..  ..  ..  ...  ...  ...  ...  ...  ...
409363 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409364 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409365 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409366 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409367 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN

[409368 rows x 10 columns]

In [20]:
rmse2 = np.sqrt(sq_all2.values.flatten()[~np.isnan(sq_all2.values.flatten())].mean())
rmse2

5.032608712853716

In [21]:
next_out

n6  n7  n8  n9  n10  n11  n12  n13  n14  n15
0      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
1      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
2      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
3      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
4      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
...     ..  ..  ..  ..  ...  ...  ...  ...  ...  ...
409363 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409364 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409365 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409366 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409367 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN

[409368 rows x 10 columns]

In [22]:
bias3 = next_out.values.flatten()[~np.isnan(next_out.values.flatten())].mean()
bias3

2.332812772961218

In [23]:
sq_all3 = next_out**2
sq_all3

n6  n7  n8  n9  n10  n11  n12  n13  n14  n15
0      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
1      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
2      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
3      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
4      NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
...     ..  ..  ..  ..  ...  ...  ...  ...  ...  ...
409363 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409364 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409365 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409366 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN
409367 NaN NaN NaN NaN  NaN  NaN  NaN  NaN  NaN  NaN

[409368 rows x 10 columns]

In [24]:
rmse3 = np.sqrt(sq_all3.values.flatten()[~np.isnan(sq_all3.values.flatten())].mean())
rmse3

4.805972264961127

In [25]:
canv_arr1 = np.array(out_bias.mean(axis=1).values)
canv_arr2 = np.array_split(canv_arr1, 444)
lat_coord = next_06['lat'].data.flatten()
lon_coord = next_06['lon'].data.flatten()
canv_arr3 = xr.DataArray(canv_arr2, coords = [lat_coord, lon_coord], dims = ['lat', 'lon'])
def ca_nv(dataarray):
    lat_drop = dataarray.where(dataarray.lat < 42, drop = True)
    lat_drop1 = lat_drop.where(lat_drop.lat > 31, drop = True)
    lon_drop2 = lat_drop1.where(lat_drop1.lon < -114, drop = True)
    return lon_drop2
canv_chop = ca_nv(canv_arr3)
canv_chop.data.flatten()[~np.isnan(canv_chop.values.flatten())].mean()

1.3562560767378773

In [27]:
sq_all = (out_bias)**2
sq_all

6   7   8   9  10  11  12  13  14  15
0      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
1      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
2      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
3      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
4      NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
...     ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
409363 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
409364 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
409365 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
409366 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
409367 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN

[409368 rows x 10 columns]